version: 2.1
orbs:
  node: circleci/node@5.0.1

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build vite-svelte app
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          sudo echo $RSYNC_SECRET > rsyncd.secret &&
          cat rsyncd.secret &&
          sudo chmod 600 rsyncd.secret
      - run: 
          name: deploy To nginx
          command: |
            rsync -avz --delete --port 873 --password-file=rsyncd.secret ./dist/ 124.71.227.249::nginx/

workflows:
  on_main_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires: 
            - build
     
