version: 2.1
orbs:
  node: circleci/node@5.0.1

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Build vite-svelte app
          command: yarn build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - attach_workspace:
          at: ~/project
      - run: 
          name: create rsyncd.secret
          command: |
            sudo $RSYNC_SECRET > /etc/rsyncd.secret
      - run: 
          name: chmod rsyncd.secret
          command: |
            sudo chmod 600 /etc/rsyncd.secrets
      - run: 
          name: print secrets
          command: |
            cat /etc/rsyncd.secret
      - run: 
          name: deploy To nginx
          command: |
            rsync -avz --delete --port 873 ./dist/ 124.71.227.249::web/

workflows:
  on_main_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires: 
            - build
     
